{{- $secretName := include "ingestion-pipeline.name" . | trim }}
{{- $pipelineName := printf "%s-pipeline" $secretName }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{- include "ingestion-pipeline.name" . }}-pipeline-config"
data:
  ingestion.py: |
{{ .Files.Get "files/ingestion.py" | replace "REPLACE_SECRET_NAME" $secretName | replace "REPLACE_PIPELINE_NAME" $pipelineName | indent 4}}