---
{{- if eq .Values.source "S3" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "ingestion-pipeline.name" . }}"
  annotations: {}
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  SOURCE: {{ .Values.source }}
  EMBEDDING_MODEL: {{ .Values.embedding_model }}
  NAME:  {{ .Values.name }}
  VERSION:  "{{ .Values.version }}"
  ACCESS_KEY_ID: {{ .Values.S3.access_key_id }}
  SECRET_ACCESS_KEY: {{ .Values.S3.secret_access_key }}
  ENDPOINT_URL: {{ .Values.S3.endpoint_url }}
  BUCKET_NAME: {{ .Values.S3.bucket_name }}
  REGION: {{ .Values.S3.region }}
{{- end }} 
