---
{{- if eq .Values.source "URL" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "ingestion-pipeline.name" . }}"
  annotations: {}
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  SOURCE: {{ .Values.source }}
  EMBEDDING_MODEL: {{ .Values.embedding_model }}
  NAME:  {{ .Values.name }}
  VERSION:  "{{ .Values.version }}"
  URLS: '{{- .Values.URL.URLS -}}'
{{- end }}