apiVersion: batch/v1
kind: CronJob
metadata:
  name: validate-embeddings
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: validate-embeddings
              image: "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest"
              command:
                - /bin/sh
                - -c
                - |
                  echo "Running script at $(date)"
                  set -o errexit
                  set -o nounset
                  set -o pipefail

                  # Get DB sha
                  DB_SHA="$(
                    oc exec "pods/$DB_HOST-0" -- bash -c \
                    "pg_dump -U $DB_USER -d $DB_NAME | sha512sum - | cut -d' ' -f1"
                  )"
                  echo "DB_SHA: $DB_SHA"
                  echo

                  mkdir -p "/tmp/bin"
                  PATH="$PATH:/tmp/bin"

                  # Get tas binaries
                  REKOR_URL="https://$(oc get routes -n trusted-artifact-signer -l "app.kubernetes.io/component=client-server" -o jsonpath="{.items[0].spec.host}")"
                  set -x
                  for BIN in cosign rekor-cli; do
                    curl --output /tmp/bin/$BIN.gz --silent $REKOR_URL/clients/linux/$BIN-amd64.gz
                    gunzip /tmp/bin/$BIN.gz
                    chmod +x /tmp/bin/$BIN
                  done

                  # Get yq
                  wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /tmp/bin/yq --quiet
                  chmod +x /tmp/bin/yq

                  # Get rekor URL
                  REKOR_URL="https://$(oc get routes -n trusted-artifact-signer -l "app.kubernetes.io/name=rekor-server" -o jsonpath="{.items[0].spec.host}")"
                  # Workaround for TAS storage issue
                  REKOR_URL="https://rekor.sigstage.dev"

                  get_record() {
                    BLOB="$1"
                    ARTIFACT_SHA="$(echo -n "$BLOB" | sha256sum - | cut -d' ' -f1)"
                    ENTRIES="$(rekor-cli search --rekor_server="$REKOR_URL" --sha "$ARTIFACT_SHA" 2>/dev/null | wc -l)"
                    if [ "$ENTRIES" == "0" ]; then
                      echo "[ERROR] Unknown database SHA."
                      exit 1
                    fi

                    UUID="$(rekor-cli search --rekor_server="$REKOR_URL" --sha="$ARTIFACT_SHA" 2>/dev/null | head -1)"
                    rekor-cli get --rekor_server="$REKOR_URL" --uuid="$UUID"
                  }

                  # Retrieve attestation
                  ATTESTATION_PATH="/tmp/attestation.json"
                  get_record "att:$DB_SHA" | yq --prettyPrint ".Attestation" > "$ATTESTATION_PATH"
                  echo "Attestation:"
                  cat "$ATTESTATION_PATH"
                  echo

                  # Retrieve signature
                  # https://search.sigstore.dev/?hash=sha256:05022c671e63971799cbe44af2631de2c0d6608b4a59214c4641af05411e28fc
                  SIGNATURE_PATH="/tmp/signature.json"
                  get_record "sig:$DB_SHA" | yq ".Body.HashedRekordObj.signature.content" > "$SIGNATURE_PATH"
                  echo "Signature:"
                  cat "$SIGNATURE_PATH"
                  echo

                  TUF_URL="https://$(oc get routes -n trusted-artifact-signer -l "app.kubernetes.io/component=tuf" -o jsonpath="{.items[0].spec.host}")"
                  export HOME="/tmp"
                  cosign initialize --mirror="$TUF_URL" --root="$TUF_URL/root.json"
                  # cosign verify-blob --key=k8s://openshift-pipelines/signing-secrets --rekor-url="$REKOR_URL" --signature rekor-file $ARTIFACT_SHA
                  # cosign verify-blob-attestation --rekor-url="$REKOR_URL"

                  # Apply policy

                  echo "Done."
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: pgvector
                      key: host
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: pgvector
                      key: dbname
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: pgvector
                      key: user
          restartPolicy: Never
          serviceAccountName: pipeline-runner-dspa
