# This secret will be used by the rag-pipeline-notebook
---
apiVersion: v1
kind: Secret
metadata:
  name: rag-ingestion-pipeline-secret
  annotations: {}
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  SOURCE: S3
  EMBEDDING_MODEL: {{ .Values.embedding_model }}
  NAME:  {{ .Values.name }}
  VERSION:  "{{ .Values.version }}"
  ACCESS_KEY_ID: {{ .Values.minio.minio_rag_user }}
  SECRET_ACCESS_KEY: {{ .Values.minio.minio_rag_password }}
  ENDPOINT_URL:  "http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000"
  BUCKET_NAME: {{ .Values.minio.bucket_name }}
  REGION: {{ .Values.minio.region }}

