---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
spec:
  dspVersion: v2
  objectStorage:
    externalStorage:
      host: {{ .Values.minio.host }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.minio.port }}
      scheme: http
      bucket: {{ .Release.Namespace }}-pipeline
      region: {{ .Values.minio.region }}
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
  apiServer:
    enableSamplePipeline: false
    managedPipelines:
      instructLab:
        state: Removed
