---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-dspa-secret
  annotations: {}
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.user }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.password }}
