{{- $models := include "llm-service.mergeModels" . | fromJson }}
{{- range $key, $model := $models }}
{{- if and $model.enabled (not $model.url) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $key }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $model.storageSize | default "50Gi" }}
  volumeMode: Filesystem
{{- end }}
{{- end }}
